version: '2'
services:
  database:
    image: postgres:9.3
    container_name: database
      
  conjur:
    image: cyberark/conjur
    container_name: conjur-master
    command: server
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY:
    depends_on: [ database ]
    ports:
      - "8080:80"

  client:
    image: conjurinc/cli5
    container_name: conjur-cli
    depends_on: [ conjur ]
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL: http://conjur-master
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_API_KEY:
      CONJUR_AUTHN_LOGIN: admin

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9090:8080"
